org.gradle.jvmargs=-Xmx1536m
org.gradle.parallel=false
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=1.16.5
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=com.carpetplayers
archives_base_name=carpetplayers

# Dependencies
fabric_api_version=0.42.0+1.16
carpet_version=1.16.5-1.4.44+v210714
